# Generated by Django 3.2.7 on 2021-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
