# Generated by Django 3.2.7 on 2021-09-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210907_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyuserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='item_like', to='main.MyuserLikes'),
        ),
    ]
