# Generated by Django 3.2.7 on 2021-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='watched',
            field=models.BooleanField(null=True),
        ),
    ]
