# Generated by Django 3.2.7 on 2021-09-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='watched',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
