# Generated by Django 3.2.7 on 2021-09-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_item_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='watched',
        ),
        migrations.AddField(
            model_name='myuser',
            name='watched',
            field=models.ManyToManyField(related_name='watched', to='main.Item'),
        ),
    ]
