# Generated by Django 3.2.7 on 2021-09-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210909_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imdb_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
