# Generated by Django 3.2.7 on 2021-09-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.ManyToManyField(blank=True, default=None, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingitem', to='main.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratinguser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
